!---------------------------------------------------------------------
!lattice ellipsoid generator - used by lammps and ovito for generate .data file and .xyz file
!---------------------------------------------------------------------
!compilation: gfortran -o lattice_ellipsoid_generator lattice_ellipsoid_generator.f90
!usage: ./lattice_ellipsoid_generator
!---------------------------------------------------------------------
!                                       1.8 version
!                                       Bruno Morini
!                                        Nov 2020
!---------------------------------------------------------------------

Implicit none
real*8 m, d, a, b, c, q, pi, gr, ga, lat, lon, x, y, z, de
integer cnt, j, i, k, n, l

  print*, 'Particle masses ? q=m'
  read*, m
  print*, 'Particle Diameter?'
  read*, d
  print*, 'Semi-axis x ? > Particle Diameter'
  read*, a
  print*, 'Semi-axis y ? > Particle Diameter'
  read*, b
  print*, 'Semi-axis z ? > Particle Diameter'
  read*, c

  !q=m*(sqrt((6.67408E-11)/(8.98755E9))) !Converting mass to charge 

  q=m

  open(1, file='ellipsoid.data')
  open(2, file='ellipsoid.xyz')
  
  cnt=0 !counter
  l=a/d !number of layers (semi-major axis/partcle diameter)

  pi=4*(atan(1.0_8)) !4 * atan (1.0_8)=pi  
  
  de=m/((4.0/3.0)*pi*((d/2.0)**3.0)) !particle density 
  
  call id(j, i, cnt, l, n, pi, d) !counter subroutne

  Write(1,*) '#LAMMPS data file via lattice_ellipsoid_generator.f90, version 1.8 Nov 2020, by Bruno Morini'
  Write(1,*) cnt+1, 'atoms'
  Write(1,*) '1 atom types'
  Write(1,*) ''
  Write(1,*)  d*(-1E5),'', d*(1E5),'', 'xlo xhi'
  Write(1,*)  d*(-1E5),'', d*(1E5),'', 'ylo yhi'
  Write(1,*)  d*(-1E5),'', d*(1E5),'', 'zlo zhi'
  Write(1,*) ''
  Write(1,*)  'Masses'
  Write(1,*) ''
  Write(1,*)  '1', q
  Write(1,*) ''
  Write(1,*)  'Atoms # hybrid'
  Write(1,*) ''
  write(1,*) '1 1 0.0000000000000000 0.0000000000000000 0.0000000000000000', d, de, q, '0 0 0' !origin particle
  
  
  Write(2,*) cnt+1
  Write(2,*) 'generated by VMD'
  write(2,*) 'c 0.0 0.0 0.0' !origin particle
  
  call xyz(gr, ga, cnt, n, pi, a, b, c, j, l, i, lat, lon, x, y, z, q, d, de, m) !subroutine objetct generator
  
  call velocity(cnt, k) !subroutine velocity particles

end
  
subroutine xyz(gr, ga, cnt, n, pi, a, b, c, j, l, i, lat, lon, x, y, z, q, d, de, m) 
Implicit none
real*8 gr, ga, pi, a, b, c, lat, lon, x, y, z, q, d, de, m
integer cnt, j, i, n, l
  
  gr=(sqrt(5.0)+1.0)/2.0 !golden ratio
  ga=(2.0-gr)*(2.0*3.1415) !golden angle
    
  cnt=1 !counter + origin particle
    
  do j=1,l  
    n=((4.0*pi*((d*j)**2.0))/(pi*(d**2.0))) !number of particle in the layer
    do i=1,n
      lat=asin(-1+2.0*i/(n+1)) !latitude
      lon=ga*i !longitude
    
      x = d*(j*cos(lon)*cos(lat)) !x coordenates particle
      y = d*((b/a)*j*sin(lon)*cos(lat)) !y coordenates particle
      z = d*((c/a)*j*sin(lat)) !z coordenates particle
        
      cnt=cnt+1

      write(1,*) cnt, '1', x, y, z, d, de, q, '0 0 0' ! write lammps data
      write(2,*) 'c', x, y, z !write vmd xyz
    enddo
  enddo  
  
  Print*, 'Number of fragments:', cnt
  Print*, 'Total Object Mass:', cnt*m
    
return
end  
  
subroutine id(j, i, cnt, l, n, pi, d) 
Implicit none
real*8 pi, d
integer j, i, cnt, n, l
  
  do j=1,l
    n=((4.0*pi*((d*j)**2.0))/(pi*(d**2.0)))
    do i=1,n
    cnt=cnt+1
    enddo
  enddo  
    
return
end

subroutine velocity(cnt, k) 
Implicit none
integer cnt, k
  
  Write(1,*) ''
  Write(1,*) 'Velocities'
  Write(1,*) ''
  
  do k=1,cnt
    write(1,*) k, '0.000000000 0.000000000 0.000000000 0.0000000000000000e+00 0.0000000000000000e+00 0.0000000000000000e+00'
  enddo  

return
end
